# Generated by Django 4.2.6 on 2025-09-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='name',
            field=models.TextField(default='Noname', verbose_name='Имя'),
        ),
    ]
