# Generated by hand: add video field to Messages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_messages_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='видео'),
        ),
    ]
