# Generated by Django 4.2.6 on 2026-03-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_video_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecandidate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
